### ISSUE TITLE
Release process: notification of content freeze

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cvs.two#354]
**Original report on BitBucket by Taina Jääskeläinen.**

----------------------------------------

This is an issue relating to the general release process. As the release requires a content freeze:

1. At the time of the freeze, the Editor should have a notification in the UI saying something like: The service is under maintenance today.
2. Notifications of the freeze start and end sent to the SL and TL admin by email. Probably by the Content Contact.

‌

**Comment by john-shepherdson** [comment]
In short term, create static 'Maintenance' page and use DNS change (with short life) to redirect users.

**Comment by matthew-morris-cessda** [comment]
The server should also return a 503 status code as well

**Comment by john-shepherdson** [comment]
@matthew-morris-cessda  Can this be used for the 3.2.0 release on 09/05/2023?

**Comment by MajaDolinar** [comment]
I believe this is resolved and we can close the issue? @john-shepherdson

**Comment by john-shepherdson** [comment]
@matthew-morris-cessda Will this be resolved for the 3.3.0 release?, if not is should be removed from the milestone

**Comment by matthew-morris-cessda** [comment]
This has been removed from the 3.3.0 milestone

**Comment by Lorenz1983** [comment]
@matthew-morris-cessda Will the issue still be resolved? If so, we can add it to the milestones again.

**Comment by Lorenz1983** [comment]
@matthew-morris-cessda Since according to your comment (September 2023) the issue has not yet been resolved, I assume that it is still open.

**Comment by matthew-morris-cessda** [comment]
Yes, this has not been resolved

**Comment by Lorenz1983** [comment]
@matthew-morris-cessda Thanks for the info. How long would it take or how much time would it take to resolve the issue?
