### ISSUE TITLE
Editing About page issue

### ISSUE THREAD

**Issue by MajaDolinar** [cessda/cessda.cvs.two#814]
There is an issue when I try to edit the About page. When I click on Edit, a table opens, however there is no text inside the row for me to edit. See screenshot:
![image](https://github.com/cessda/cessda.cvs.two/assets/72601736/1fa1661e-944b-4056-ac8c-6ff7c011efc5)

**Comment by MajaDolinar** [comment]
I tried on dev to copy the text first and then copy it in the empty row. It worked, I could edit and save (it showed green success confirmation text). But then when I would click on About again, the text was the old text again. 
So this solution does not work. Please see what is going on.

**Comment by john-shepherdson** [comment]
V3.3.0 release cannot be announced until this is fixed

**Comment by matthew-morris-cessda** [comment]
This is resolved on staging

![image](https://github.com/cessda/cessda.cvs.two/assets/68543725/b9668a40-065f-4d6d-ab06-08fcec726965)

**Comment by MajaDolinar** [comment]
Great, I see it working now perfectly. When will it be possible to see this on production?

**Comment by matthew-morris-cessda** [comment]
I should be able to get this released tomorrow if no other issues are found

**Comment by MajaDolinar** [comment]
Great, keep me posted :-)

**Comment by MajaDolinar** [comment]
When will this be resolved on production? I checked and it is still not working there. I need to update the version number in order to send out info that the new release occurred. Please let me know when this will be possible.

**Comment by matthew-morris-cessda** [comment]
This will be resolved in production today if all goes well
